Attempt to fix missing citation info on the multi_gene_plots vignette
From https://bioconductor.org/checkResults/devel/data-experiment-LATEST/spatialLIBD/nebbiolo1-buildsrc.html

```
* creating vignettes ... ERROR
--- re-building ‘TenX_data_download.Rmd’ using rmarkdown
--- finished re-building ‘TenX_data_download.Rmd’

--- re-building ‘guide_to_spatial_registration.Rmd’ using rmarkdown
--- finished re-building ‘guide_to_spatial_registration.Rmd’

--- re-building ‘multi_gene_plots.Rmd’ using rmarkdown

Quitting from lines 340-345 (multi_gene_plots.Rmd)
Error: processing vignette 'multi_gene_plots.Rmd' failed with diagnostics:
subscript out of bounds
--- failed re-building ‘multi_gene_plots.Rmd’

--- re-building ‘spatialLIBD.Rmd’ using rmarkdown
--- finished re-building ‘spatialLIBD.Rmd’

SUMMARY: processing the following file failed:
  ‘multi_gene_plots.Rmd’
```